name: codebox-test
icon: acid
code-server:
  proxy-domain: homer0.com
  # codebox$
  hashed-password: 64aad9f2edfd5658acc3929b840bf0dd64c374a2edd85ee71ec78eafb30740b9
vscode:
  extensions:
    # Atom Keymap
    - ms-vscode.atom-keybindings
    # Beautify
    - HookyQR.beautify
    # CodeSnap
    - adpyke.codesnap
    # EditorConfig for VS Code
    - EditorConfig.EditorConfig
    # EJS language support
    - DigitalBrainstem.javascript-ejs-support
    # ESLint
    - dbaeumer.vscode-eslint
    # Prettier
    - esbenp.prettier-vscode
    # file-icons
    - file-icons.file-icons
    # Sass
    - syler.sass-indented
    # Svelte for VS Code
    - svelte.svelte-vscode
    # Prisma
    - Prisma.prisma
    # Version Lens
    - pflannery.vscode-versionlens
git:
  username: homer0
  email: me@homer0.dev

