names:
  container: codebox-container
  image: codebox
ports:
  http: 5580
  https: 5581
  ssh: 5522
  code-server: 6581
paths:
  mount:
    config: /config
    profile: /profile
  setup: /dev/box
  code: /
