name: Release NPM package

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo "::set-output name=NVMRC::$(cat .nvmrc)"
        id: nvm
      - uses: actions/setup-node@v2
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - name: Install dependencies
        run: npm ci
      - run: npm run dev:image:create && npx semantic-release
        env:
          DOCKER_PASSWORD: ${{ secrets.PACKAGE_TOKEN }}
          DOCKER_USER: homer0
